# Generated by Django 3.1.5 on 2021-01-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(through='main.ExamQuestion', to='main.Question'),
        ),
    ]
