# Generated by Django 3.1.5 on 2021-01-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210126_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='main.Student'),
        ),
        migrations.AlterField(
            model_name='school',
            name='teachers',
            field=models.ManyToManyField(blank=True, null=True, to='main.Teacher'),
        ),
    ]
