# Generated by Django 3.1.5 on 2021-01-26 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_exam_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examquestion',
            old_name='question',
            new_name='question_id',
        ),
        migrations.AlterUniqueTogether(
            name='examquestion',
            unique_together={('exam', 'question_id')},
        ),
    ]
