# Generated by Django 3.1.5 on 2021-01-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210126_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(to='main.Student'),
        ),
        migrations.DeleteModel(
            name='ClassStudent',
        ),
    ]
