# Generated by Django 3.1.5 on 2021-01-26 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210126_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='questions',
            new_name='question',
        ),
    ]
