# Generated by Django 3.1.5 on 2021-01-26 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210126_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.exam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='examinar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('student', 'exam', 'question')},
        ),
        migrations.RemoveField(
            model_name='submission',
            name='eq',
        ),
    ]
